title: Rohit Prakash
first_name: Rohit
middle_name: P.
last_name: Prakash
contact_note: >
  I'm open to collaborations, research ideas, and exciting embedded/AI opportunities.
description: >
  A minimalist, elegant portfolio to showcase my journey as an embedded systems engineer, AI enthusiast, and persistent learner.
footer_text: >
  Built with ❤️ using <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> & <a href="https://github.com/alshedivat/al-folio">Al-Folio</a>.
keywords: rohit prakash, embedded, ai, systems engineer, portfolio
lang: en
icon: ⚡

url: "https://rohxander.github.io"
baseurl: ""

last_updated: true
back_to_top: true

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: false
max_width: 930px

repo_theme_light: default
repo_theme_dark: dark

rss_icon: true

author:
  name: "Rohit Prakash"
  avatar: "/assets/img/avatar.jpg"
  bio: "Engineer passionate about embedded systems, AI, and meaningful technology."
  location: "Germany"
  links:
    - label: "GitHub"
      url: "https://github.com/rohxander"
      icon: "fab fa-github"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/YOUR-LINKEDIN"
      icon: "fab fa-linkedin"
    - label: "Email"
      url: "mailto:your.email@example.com"
      icon: "fas fa-envelope"

blog_name: "Tech & Thoughts"
blog_description: "A mix of embedded systems, AI, culture, and personal insights."
permalink: /blog/:year/:title/
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

collections:
  projects:
    output: true

enable_project_categories: true
enable_masonry: true
enable_math: true
enable_darkmode: true
enable_medium_zoom: true
enable_progressbar: true
enable_navbar_social: true

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate-v2
  - jekyll-archives-v2

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
